### ISSUE TITLE
General Message Structure in JSON compatible YAML v1.2

### ISSUE THREAD

**Issue by hgn** [protocollabs/ietf-drafts#11]
I think we should avoid YAML. It just adds an additional indirection makes it hard to understand it. I.e. the user is required to know JSON **and** YAML. This is too much. Take a look at (RFC 7951, JSON Encoding of Data Modeled with YANG)[https://tools.ietf.org/html/rfc7951]

**Comment by reisub-de** [comment]
Yeah, you are right. JSON just felt so verbose while writing but it is still better than yaml.
Thanks for the rfc, that looks handy
