### ISSUE TITLE
Table or List

### ISSUE THREAD

**Issue by hgn** [protocollabs/ietf-drafts#12]
https://github.com/protocollabs/ietf-drafts/blob/5d81981676e5f5ba5b10601aac77b08f9d0f4472/draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.txt#L198-L205

I like the table somehow, we should probably left align the table content? On the other hand: a itemize list looks shitty, right?

**Comment by reisub-de** [comment]
Yeah, itemize doesn't fit there I think. I will take a look at left-aligning
