### ISSUE TITLE
DMPR Abstract

### ISSUE THREAD

**Issue by hgn** [protocollabs/ietf-drafts#22]
I wrote a first abstract. I am not really satified, but I think it is a good starting point. The idea of an abstract is to make it clear what DMPR is and what is provide: "Is DMPR what I am looking for?". It should highlight is main feature points and promote itself.

Here the link to the first version of the abstract:

https://github.com/protocollabs/ietf-drafts/blob/c45eb2a2e3ddb783ef99af28ea7a69a24a5d780e/draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.txt#L16

**Comment by reisub-de** [comment]
https://github.com/protocollabs/ietf-drafts/blob/c45eb2a2e3ddb783ef99af28ea7a69a24a5d780e/draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.xml#L119-L120

Is the feature set really that similar? One feature of BGP is that you directly and explicitly connect with your peers and can define rules on what routes to accept and forward. This would probably break dmpr which assumes every node behaves the same.

The feature set is more similar to babel imho.

**Comment by reisub-de** [comment]
Small changes: eed20a83f9e444ee9e455c33dab8a4bef01036b8

**Comment by hgn** [comment]
Ack, I want to differentiate dmpr from bgp, babel and other routing protocols. Please think about this! Why should I prefer dmpr over foo?
