### ISSUE TITLE
Fragmentation Header - Identification Length

### ISSUE THREAD

**Issue by reisub-de** [protocollabs/ietf-drafts#8]
https://tools.ietf.org/html/rfc2460#section-4.5

>  For every packet that is to be fragmented, the source node generates
   an Identification value. The Identification must be different than
   that of any other fragmented packet sent recently* with the same
   Source Address and Destination Address.  If a Routing header is
   present, the Destination Address of concern is that of the final
   destination.
\* "recently" means within the maximum likely lifetime of a packet,
        including transit time from source to destination and time spent
        awaiting reassembly with other fragments of the same packet.
        However, it is not required that a source node know the maximum
        packet lifetime.  Rather, it is assumed that the requirement can
        be met by maintaining the Identification value as a simple, 32-
        bit, "wrap-around" counter, incremented each time a packet must
        be fragmented.  It is an implementation choice whether to
        maintain a single counter for the node or multiple counters,
        e.g., one for each of the node's possible source addresses, or
        one for each active (source address, destination address)
        combination.

As we are only sending very few packets I think it is sufficient to go with a 8-bit identification field

**Comment by hgn** [comment]
OK, can you take a look at [RFC 6980, Security Implications of IPv6 Fragmentation with IPv6 Neighbor Discovery](https://tools.ietf.org/html/rfc6980)?

**Comment by reisub-de** [comment]
Possible Problems are:
- IPv6 Fragmentation can be used to circumvent packet inspection guards against Neighbor Discovery attacks
- denial of service when an attacker sends colliding identifications

As dmpr currently is neither encrypted nor signed so this is a problem anyway.
It could be mitigated by a HMAC Extension Header in every packet which provides a method to ensure there is no packet spoofing. If the fragmentation header is also signed by the HMAC then 8 bits should be sufficient

**Comment by hgn** [comment]
OK, leave it for now, ... Further improvement, v2, thank you!
